### ISSUE TITLE
remove assets/*.js and assets/vendor.css. Move only the styles needed into assets/camp.css

### ISSUE THREAD

**Issue by gr2m** [sohini-roy/hoodie-camp-static#1]
You’ll find the styles in these files:
https://github.com/hoodiehq/camp/tree/master/app/styles

Also remove loading `assets/vendor.css` from the HTML files and remove the `integrity` property from the `<link rel="stylesheet" href="assets/camp.css" integrity="...">` tags

**Comment by sohini-roy** [comment]
I am working on it :)
