### ISSUE TITLE
do not log the github token

### ISSUE THREAD

**Issue by gr2m** [sohini-roy/hoodie-camp-static#2]
you currently log the github token that a user enters, can you please remove that?

**Comment by sohini-roy** [comment]
Deleting that right away..I did that to check if my code was working :)

**Comment by gr2m** [comment]
Great :)

I would suggest you make pull requests for the different issues, and once the PRs get merged, the issue should be closed. If you put `closes #123` into the pull request description, the issue gets closed automatically when you merge the PR :) That way everyone is up to date on what issues you are working on, what issues are still open and what issues are still open. 

I think we can closes this issue now, it’s been fixed in https://github.com/sohini-roy/hoodie-camp-static/commit/99778c87c753db40403d04b7fd8d871be097874a, right?

**Comment by sohini-roy** [comment]
yes..it can be closed now.Thanks for helping :)
